---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/stwomack/account-service.git
    branch: master

- name: cf
  type: cf
  source:
    api: https://api.pcf1.fe.gopivotal.com
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: test-and-deploy
  public: true
  serial: true
  plan:
  - get: source-code
    trigger: true
  - task: build-and-run-tests
    file: source-code/ci/build.yml
  - put: cf
    params:
      manifest: source-code/manifest.yml
      path: build-output/account-service-0.0.1-SNAPSHOT.jar